---

- name: Fix sysctl for controller
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present sysctl_set=yes
  with_items:
    - { name: "net.ipv4.ip_nonlocal_bind", value: 1 }
  tags: controller_main

- name: Check internal virtual IP is set
  command: ip add ls {{nics.manage}}
  register: int_ip_check
  changed_when: no
  tags: controller_main
  
- name: Set internal virtual IP on master controller
  command: "ip addr add {{int_virtual_ip}}/32 dev {{nics.manage}} "
  when: is_master_controller and int_virtual_ip not in int_ip_check.stdout
  tags: controller_main

- name: Check external virtual IP is set
  command: ip add ls {{nics.public_infra}}
  register: ext_ip_check
  changed_when: no
  tags: controller_main
  
- name: Set external virtual IP on master controller
  command: "ip addr add {{ext_virtual_ip}}/32 dev {{nics.public_infra}} "
  when: is_master_controller and ext_virtual_ip not in ext_ip_check.stdout
  tags: controller_main

- name: Make sure ssl keys dir exists
  file:
    path: "{{ssl_dir}}"
    recurse: true
    state: directory

- name: Upload ssl key
  copy: content="{{ssl_key}}" dest="{{ssl_key_path}}" setype="etc_t"
  tags: controller_main
  
- name: Uplaod ssl pem
  copy: content="{{ssl_pem}}" dest="{{ssl_pem_path}}" setype="etc_t"
  tags: controller_main
  
- include: rabbitmq.yml
  when: is_master_controller
  
- include: mysql.yml
  when: is_master_controller
  
- include: keystone.yml
- include: nginx.yml
- include: glance.yml
- include: nova.yml
- include: neutron.yml
- include: cinder.yml
- include: ceilometer.yml
- include: heat.yml
