---
- name: Add MySQL community repo
  yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present
  tags: controller_mysql

- name: Install MySQL server and client
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-connector-python
    - MySQL-python
  tags: controller_mysql

- name: Start MySQL service
  service: name=mysql state=running enabled=true
  tags: controller_mysql

- name: Check MySQL root password is set
  command: mysql -e "select 1"
  register: mysql_root_access
  changed_when: no
  tags: controller_mysql
  
- name: Secures the MySQL localhost root user
  mysql_user:
    user="root"
    password="{{ mysql_root_pass }}"
    host=localhost
  tags: controller_mysql
  when: mysql_root_access.rc == 0

- name: Secures the MySQL for all root accounts
  mysql_user:
    user="root"
    password="{{ mysql_root_pass }}"
    host="{{ item }}"
    login_user=root
    login_password="{{ mysql_root_pass}}"
  with_items:
    - "{{ ansible_fqdn }}"
    - 127.0.0.1
    - ::1
  tags: controller_mysql
  
- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ mysql_root_pass }}" login_user=root

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ mysql_root_pass }}" login_user=root
  tags: controller_mysql

