---
- name: Ensure RPMs for Neutron Server
  yum: name="{{item}}" state="present"
  with_items:
    - 'openstack-neutron'
    - 'openstack-neutron-ml2'
    - 'python-neutronclient'
    - 'python-neutron-lbaas'
    - 'python-neutron-vpnaas'
    - 'openstack-neutron-lbaas'
    - 'openstack-neutron-vpnaas'
  tags: controller_neutron
  
- name: Update Neutron Server conf
  setosconf:
    dest="/etc/neutron/neutron.conf"
    section="{{item.0}}"
    option="{{item.1}}"
    value="{{item.2}}"
  with_nested:
    - neutron_server_conf_vals
  tags: controller_neutron
  
- include: set_keystone_conf_vals.yml service_username="neutron" dest="/etc/neutron/neutron.conf"
  tags: controller_neutron 

- include: set_rabbit_conf_vals.yml dest="/etc/neutron/neutron.conf"
  tags: controller_neutron

- include: "set_ml2_conf.yml"
  tags: controller_neutron
  
- include: create_service_db.yml service_name="neutron" db_pass="{{neutron_db_pass}}"
  when: is_master_controller  
  tags: controller_neutron
  
- name: Neutron DB sync
  command: "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini upgrade head"
  when: is_master_controller    
  tags: controller_neutron
  
- name: LBAAS DB sync
  command: "neutron-db-manage --service lbaas upgrade head"
  when: is_master_controller  
  tags: controller_neutron
  
- name: VPNAAS DB sync
  command: "neutron-db-manage --service vpnaas upgrade head"
  when: is_master_controller    
  tags: controller_neutron

- name: Restart Nova services related to Neutron setup
  service: name="openstack-nova-{{item}}" state="restarted"
  with_items:
    - api
    - scheduler
    - conductor
  when: is_master_controller
  tags: controller_neutron
  
- name: Ensure Neutron Server service running/enabled
  service: name="neutron-server" state="running" enabled=True
  when: is_master_controller    
  tags: controller_neutron
