---

- name: Ensure RPMs for Compute node
  yum: name="{{item}}" state="present"
  with_items:
    - 'openstack-nova-compute'
    - 'sysfsutils'
    - 'libguestfs-tools'
    - 'openstack-neutron'
    - 'openstack-neutron-ml2'
    - 'openstack-neutron-openvswitch'
  tags: compute_main

- name: Load bridge module
  command: "brctl show"
  tags: compute_main
  
- name: Ensure sysctl settings
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present sysctl_set=yes
  with_items:
    - { name: "net.ipv4.ip_nonlocal_bind", value: 1 }
    - { name: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { name: "net.ipv4.conf.all.rp_filter", value: 0 }
    - { name: "net.ipv4.conf.default.rp_filter", value: 0 }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
    - { name: "net.nf_conntrack_max", value: "524288" }
  tags: compute_main

- name: Setup repos for qemu rhev
  copy: src="{{item}}" dest="/etc/yum.repos.d/{{item}}"
  with_items:
    - qemu-kvm-rhev.repo
    - glusterfs-epel.repo
  tags: compute_main

- name: Install qemu-kvm-ev
  yum: name=qemu-kvm-ev state=present
  tags: compute_main
  
- name: Ensure br-int bridge
  openvswitch_bridge: name='br-int' state='present'
  tags: compute_main

- name: Set Neutron related vals in nova.conf
  setosconf:
    dest: /etc/nova/nova.conf
    section: '{{item.0}}'
    option: '{{item.1}}'
    value: '{{item.2}}'
  with_nested:
    - nova_compute_network_vals
  notify: restart nova compute    
  tags: compute_neutron

- name: Set neutron.conf on compute node
  setosconf:
      dest="/etc/neutron/neutron.conf"
      section="{{item.0}}"
      option="{{item.1}}"
      value="{{item.2}}"
  with_nested:
    - neutron_compute_vals
  notify: restart neutron on compute
  tags: compute_neutron

- include: ../../common/tasks/set_keystone_conf.yml  dest="/etc/neutron/neutron.conf" service_name="neutron"
  tags: compute_neutron

- include: ../../common/tasks/set_rabbit_conf.yml dest="/etc/neutron/neutron.conf" 
  tags: compute_neutron
  
- include: ../../network/tasks/set_ml2_conf.yml
  tags: compute_neutron