---
compute_node_rdo_services:
  - openstack-nova-compute
  - neutron-openvswitch-agent

# values in nova.conf on compute node related to compute
nova_compute_vals:
  - [ 'database', 'connection', 'mysql://nova:{{nova_db_pass}}@127.0.0.1/nova' ]
  - [ 'DEFAULT', 'my_ip', "{{hostvars[inventory_hostname]['ansible_' + nics.data]['ipv4'].address}}" ]
  - [ 'DEFAULT', 'vnc_enabled', True ]
  - [ 'DEFAULT', 'vncserver_listen', "{{hostvars[inventory_hostname]['ansible_' + nics.manage]['ipv4'].address}}" ]
  - [ 'DEFAULT', 'resume_guests_state_on_host_boot', True ]
  - [ 'DEFAULT', 'os_region_name', "{{region}}" ]
  - [ 'DEFAULT', 'vif_plugging_is_fatal', False ]
  - [ 'DEFAULT', 'vif_plugging_timeout', 0 ]
  - [ 'DEFAULT', 'remove_unused_base_images', False ]
  - [ 'DEFAULT', 'default_ephemeral_format', 'ext4' ]
  - [ 'DEFAULT', 'state_path', '/var/lib/nova' ]
  - [ 'DEFAULT', 'novncproxy_base_url', "{{ext_base_url}}:6080/vnc_auto.html" ]
  
# values in nova.conf on compute node related to networking
nova_compute_network_vals:
  - [ 'DEFAULT', 'network_api_class', 'nova.network.neutronv2.api.API']
  - [ 'DEFAULT', 'security_group_api', 'neutron']
  - [ 'DEFAULT', 'linuxnet_interface_driver', 'nova.network.linux_net.LinuxOVSInterfaceDriver']
  - [ 'DEFAULT', 'firewall_driver', 'nova.virt.firewall.NoopFirewallDriver']
  - [ 'neutron', 'url', '{{int_virtual_ip}}:9696']
  - [ 'neutron', 'auth_strategy', 'keystone']
  - [ 'neutron', 'admin_auth_url', '{{auth_token_url}}']
  - [ 'neutron', 'admin_tenant_name', 'service']
  - [ 'neutron', 'admin_username', 'neutron']
  - [ 'neutron', 'admin_password', '{{service_pass}}']
  - [ 'neutron', 'service_metadata_proxy', True ]
  - [ 'neutron', 'metadata_proxy_shared_secret', '{{neutron_metadata_secret}}']

# values for neutron.conf on compute nodes
neutron_compute_vals:
  - [ 'DEFAULT', 'core_plugin', 'ml2' ]
  - [ 'DEFAULT', 'service_plugins', 'router' ]
  