---
mongo_repo_path: /etc/yum.repos.d/mongodb.repo
mongo_repo_content: |
  [mongodb]
  name=MongoDB Repository
  baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
  gpgcheck=0
  enabled=1
mongo_bind_ip: "{{hostvars[inventory_hostname]['ansible_'+nics.manage]['ipv4'].address}}"
mongo_dbpath: "/var/lib/mongo"
mongo_user_admin: "cnadmin"
mongo_user_admin_pass: "{{vault_mongo_user_admin_pass}}"
mongo_root: "root"
mongo_root_pass: "{{vault_mongo_root_pass}}"


  