---
# file: group_vars/all/vars.yml

rdo_repo: https://rdoproject.org/repos/rdo-release.rpm
ntpserver: ntp.citynetwork.se
timezone: CET
# iptables stuff
trusted_networks:
  - manage
  - data
  - storage
is_secure: False
ssh_allowed_ips:
  - 91.123.199.0/24
  - 91.123.192.0/24
  - 91.106.192.192/27
  - 141.255.187.160/27
  - 59.167.120.216/32
  - 91.123.195.164
# vars from group's vault
service_pass: "{{vault_service_pass}}"
mysql_root_pass: "{{vault_mysql_root_pass}}"
admin_pass: "{{vault_admin_pass}}"
admin_token: "{{vault_admin_token}}"
keystone_db_pass: "{{vault_keystone_db_pass}}"
glance_db_pass: "{{vault_glance_db_pass}}"
heat_db_pass: "{{vault_heat_db_pass}}"
cinder_db_pass: "{{vault_cinder_db_pass}}"
nova_db_pass: "{{vault_nova_db_pass}}"
  
ipset_val: ""
controller_public_ports: [5000, 35357, 8080, 8004, 9292, 8776, 6080, 8773, 8774, 8775,  9696, 443, 80, 6080]
# end iptables

int_base_url: "http://int.{{server_name}}"
ext_base_url: "https://{{server_name}}"
auth_url: "{{int_base_url}}:35357"
auth_uri: "{{ext_base_url}}:5000"

keystone_authtoken_vals:
  - [ 'auth_uri', "{{auth_uri}}" ]
  - [ 'auth_url', "{{auth_url}}"]
  - [ 'auth_plugin', 'password']
  - [ 'project_domain_id', "default"]
  - [ 'user_domain_id', 'default']
  - [ 'project_name', 'service']
  - [ 'username', "{{service_username}}" ]
  - [ 'password', "{{service_pass}}" ]


glance_filesystem_store_datadir: "/var/lib/glance/images/"
# ssl params
ssl_pem: "{{vault_ssl_pem}}"
ssl_key: "{{vault_ssl_key}}"
ssl_dir: "/var/ssl"
ssl_pem_path: "{{ssl_dir}}/ssl_citycloud.pem"
ssl_key_path: "{{ssl_dir}}/ssl_citycloud.key"
# end ssl params

is_master_controller: "{{inventory_hostname==groups['controller'][0]}}"
#RabbitMQ section
rabbitmq_rpm_url: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.1/rabbitmq-server-3.6.1-1.noarch.rpm
rabbitmq_host: "{{groups['controller'][0]}}"
rabbitmq_virtual_host: os
rabbitmq_user: os
rabbitmq_password: "{{vault_rabbitmq_password}}"
rabbitmq_admin: city
rabbitmq_admin_password: "{{vault_rabbitmq_admin_password}}"
# end RabbitMQ section

# OpensStack services definitions
keystone_service_def:
  name: keystone
  user: keystone
  type: identity
  description: "Keystone Identity Service"
  public_url: "{{auth_url}}"
  internal_url: "{{auth_uri}}"
# the reason we have keystone_service separated is b/c
# not all DCs have Keystone service running
# _def is b/c there is module keystone_service
openstack_services:
  - name: nova
    user: nova
    type: compute
    description: "Nova Compute Service"
    public_url: "{{ext_base_url}}:8774/v2/%(tenant_id)s"
    internal_url: "{{int_base_url}}:8774/v2/%(tenant_id)s"
  - name: volume
    user: cinder
    type: volume
    description: "Cinder - Nova Volume Service"
    public_url: "{{ext_base_url}}:8776/v1/%(tenant_id)s"
    internal_url: "{{ext_base_url}}:8776/v1/%(tenant_id)s"
  - name: cinderv2
    user: cinder
    type: volumev2
    description: "Cinder - Nova Volume Service v2"
    public_url: "{{ext_base_url}}:8776/v2/%(tenant_id)s"
    internal_url: "{{ext_base_url}}:8776/v2/%(tenant_id)s"
  - name: glance
    user: glance
    type: image
    description: "Glance Image Service"
    public_url: "{{ext_base_url}}:9292"
    internal_url: "{{int_base_url}}:9292"
  - name: neutron
    user: neutron
    type: network
    description: "OpenStack Networking Service"
    public_url: "{{ext_base_url}}:9696"
    internal_url: "{{int_base_url}}:9696"
  - name: heat
    user: heat
    type: orchestration
    description: Orchestration
    public_url: "{{ext_base_url}}:8004/v1/%(tenant_id)s"
    internal_url: "{{int_base_url}}:8004/v1/%(tenant_id)s"
  - name: heat-cfn
    user: heat
    type: cloudformation 
    description: Orchestration
    public_url: "{{ext_base_url}}:8000/v1"
    internal_url: "{{ext_base_url}}:8000/v1"
  - name: metering
    user: ceilometer    
    type: metering
    description: Telemetry
    public_url: "{{ext_base_url}}:8777"
    internal_url: "{{int_base_url}}:8777"
#end OpensStack services definitions
