---

- name: Upgrade all packages
  yum: name=* state=latest

- name: Install opt repo if on RHEL
  command: subscription-manager repos --enable rhel-7-server-optional-rpms
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install common RPMs
  yum: state=present name={{ item }}
  with_items:
    - sudo
    - dbus
    - openssl-devel
    - emacs-nox
    - git
    - python-lxml
    - tcpdump
    - yum-cron
    - epel-release
    - iptables
    - iptables-services
    - libxslt-devel
    - wget
    - nfs-utils
    - yum-plugin-priorities

- name: Setup RDO repo
  yum: state=present name="{{ rdo_repo }}"

- name: Setup common OpenStack RPMs
  yum: state=present name={{ item }}
  with_items:
    - python-pip
    - openstack-utils
    - openstack-selinux
 